USE [master]
GO

/****** Object:  Database [BD_ArandaSoft]    Script Date: 23/01/2022 9:11:58 p. m. ******/
CREATE DATABASE [BD_ArandaSoft]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_ArandaSoft', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER2019\MSSQL\DATA\BD_ArandaSoft.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_ArandaSoft_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER2019\MSSQL\DATA\BD_ArandaSoft_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_ArandaSoft].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_ArandaSoft] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_ArandaSoft] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_ArandaSoft] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BD_ArandaSoft] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_ArandaSoft] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET RECOVERY FULL 
GO

ALTER DATABASE [BD_ArandaSoft] SET  MULTI_USER 
GO

ALTER DATABASE [BD_ArandaSoft] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_ArandaSoft] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_ArandaSoft] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_ArandaSoft] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BD_ArandaSoft] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_ArandaSoft] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BD_ArandaSoft] SET  READ_WRITE 
GO


